### ISSUE TITLE
I would like to have better feedback when `severless deploy` is provisioning an NPM module

### ISSUE THREAD

**Issue by jcenturion** [auth0/serverless-webtasks#9]
The process takes too long and as a user I though the process was broken.

```
Serverless: Packaging service...
Serverless: Packaging disabled for function: "main"
Serverless: Deploying function: main...
```

**Comment by rwtombaugh** [comment]
This is fixed. After 5 seconds of waiting, a message will get displayed:
<img width="738" alt="screen shot 2017-09-19 at 3 14 47 pm" src="https://user-images.githubusercontent.com/1031969/30618102-d665822c-9d4d-11e7-96fd-8cf0496a42e5.png">

If there is more than 1 module, it gives the number of modules instead of the name of the module
